### ISSUE TITLE
Nvidia Geforce Overlay causes webcam to freeze.

### ISSUE THREAD

**Issue by Whoops-all-chaingunners** [CardinalCyn/OctoCam#2]
In OctoCam, when you pull the feed, Nvidia Geforce Overlay activates (confirmed by the pop up) and the webcam freezes when viewing the URL generated on a browser. This also happens in Yawcam by the way so perhaps isn't something that can be fixed in your software. 

Disabling the overlay causes the issue to resolve.

The CMD window shows errors but they are also there when it is working:

[ WARN:1@87.213] global cap_msmf.cpp:471 `anonymous-namespace'::SourceReaderCB::OnReadSample videoio(MSMF): OnReadSample() is called with error status: -1072873821
[ WARN:1@87.215] global cap_msmf.cpp:483 `anonymous-namespace'::SourceReaderCB::OnReadSample videoio(MSMF): async ReadSample() call is failed with error status: -1072873821
[ WARN:0@87.228] global cap_msmf.cpp:1759 CvCapture_MSMF::grabFrame videoio(MSMF): can't grab frame. Error: -1072873821
127.0.0.1 - - [24/Sep/2023 21:42:59] "GET /stream/0/1920/1080 HTTP/1.1" 200 -
127.0.0.1 - - [24/Sep/2023 21:43:25] "GET /stream/0/1920/1080 HTTP/1.1" 200 -
[ WARN:4@124.197] global cap_msmf.cpp:471 `anonymous-namespace'::SourceReaderCB::OnReadSample videoio(MSMF): OnReadSample() is called with error status: -1072873821
[ WARN:4@124.199] global cap_msmf.cpp:483 `anonymous-namespace'::SourceReaderCB::OnReadSample videoio(MSMF): async ReadSample() call is failed with error status: -1072873821
[ WARN:3@124.201] global cap_msmf.cpp:1759 CvCapture_MSMF::grabFrame videoio(MSMF): can't grab frame. Error: -1072873821
127.0.0.1 - - [24/Sep/2023 21:43:36] "GET /stream/0/1920/1080 HTTP/1.1" 200 -
[ WARN:6@249.802] global cap_msmf.cpp:471 `anonymous-namespace'::SourceReaderCB::OnReadSample videoio(MSMF): OnReadSample() is called with error status: -1072873821
[ WARN:6@249.806] global cap_msmf.cpp:483 `anonymous-namespace'::SourceReaderCB::OnReadSample videoio(MSMF): async ReadSample() call is failed with error status: -1072873821
[ WARN:5@249.809] global cap_msmf.cpp:1759 CvCapture_MSMF::grabFrame videoio(MSMF): can't grab frame. Error: -1072873821

**Comment by CardinalCyn** [comment]
Were you able to resolve this? I don't really know if I can take a look at this. It doesn't seem like the code I have can grab the camera frame with that overlay.

**Comment by Whoops-all-chaingunners** [comment]
> Were you able to resolve this? I don't really know if I can take a look at this. It doesn't seem like the code I have can grab the camera frame with that overlay.

No I switched to a Raspberry pi and some Arducam modules.
